name: tracker

description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.2.2
  get: ^4.6.6
  getx_base_classes: ^0.0.2
  loading_indicator: ^3.1.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  intl: ^0.20.2
  device_info_plus: ^11.3.3
  logger: ^2.5.0
  package_info_plus: ^8.1.2
  shared_preferences: ^2.3.5
  sizer: ^3.0.4
  permission_handler: ^12.0.1
  dropdown_button2: ^2.3.9
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.2.1
  keyboard_avoider: ^0.2.0
  flutter_svg: ^2.0.17
  fl_chart: ^1.1.0
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.6
  calendar_date_picker2: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.2.0
  lottie: ^3.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^5.0.0


flutter_native_splash:
  color: "#081E21"
  image: assets/images/kalyanLogowhite.png
  android: true
  ios: true

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/kalyanlogo.png
    - assets/fonts/
    - assets/lottie/
    - assets/lottie/piggy.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Lato-Regular.ttf
 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/LOGO.jpg" # Fallback image
  remove_alpha_ios: true

  
    


     
       